using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.AI;

/// <summary>
/// Draws a line between the waypoints of the pathing solution generated by attached NavMeshAgent.
/// </summary>

[RequireComponent(typeof(NavMeshAgent))]
public class PathingLine : MonoBehaviour {
	
	NavMeshAgent navMesh;
	LineRenderer drawnLine;

	void Start () {

		navMesh = GetComponent<NavMeshAgent>();	
		drawnLine = this.gameObject.AddComponent<LineRenderer>();

		drawnLine.material = new Material ( Shader.Find( "Sprites/Default" ) ) { color = Color.red};
		drawnLine.startWidth = 0.1f;
		drawnLine.endWidth = 0.1f;
		drawnLine.startColor = Color.red;
		drawnLine.endColor = Color.red;



	}
		

	void Update () 
	{

		drawnLine.positionCount = navMesh.path.corners.Length;
		drawnLine.SetPositions(navMesh.path.corners);

	}
	
}
